### ISSUE TITLE
[Discussion] Could use 'hover-link' api to trigger popover

### ISSUE THREAD

**Issue by playermiller109** [aoout/obsidian-highlighter#8]
Hi @aoout I found `this.app.workspace.trigger('hover-link', {})` api in discord [here is the post](https://discord.com/channels/686053708261228577/840286264964022302/1018705800962785421), maybe it will be more convenient if your highlight has a target file as you said.

I wrote a simple demo to test, approximately like this:

```js
popover = (mouseEvt, tarFile)=> {
  if (!mouseEvt.ctrlKey || !tarFile) return
  this.app.workspace.trigger('hover-link', {
    event: mouseEvt,
    source: 'ample-preview',
    hoverParent: {},
    targetEl: mouseEvt.target,
    linktext: tarFile.path
  })
}
// other possible expressions...
p.innerEl.onmouseover = evt=> this.popover(evt, fdNote)
p.innerEl.onmousemove = evt=> this.popover(evt, fdNote)
```

The api should be native so it is compatible with Hover Editor plugin.

Test gif in v1.6.3:

<image width="500" src="https://github.com/aoout/obsidian-highlighter/assets/145541890/9933f64a-4a88-4660-9461-20dc72c58630">

**Comment by aoout** [comment]
Thanks for your suggestion. A highlight does have a target file, but there is not a one-to-one correspondence between them. Specifically, an md note may store any number of highlights. So I probably can't use the method you mentioned.
Anyway, glad to know something new.

**Comment by aoout** [comment]
But it does remind me that there might be some more official way to do this. Like registerHoverLinkSource. I have no idea what this is.

**Comment by playermiller109** [comment]
@aoout I've found [another post](https://discord.com/channels/686053708261228577/840286264964022302/1218326718604116061) in discord explains `registerHoverLinkSource()`. It seems the right way is:

- Use plugin name (such as 'Ample') to register `hover source` string (such as 'ample-preview').
- Set `defaultMod: true`.

Then it will automatically trigger only when `ctrlKey: true`. No need to check `if (!mouseEvt.ctrlKey)`.
Haven't tried yet.

Since a note may store multiple highlights, are there signs can identify each one, like obsidian block links? Triggering a hover-link equals simulating mouse moving on an internal link. `targetEl` refers to link's HTML element, and `linktext` refers to plain text in `[[]]`.

For example, `linktext` below is equal to `[[filePath#Test]]`. Trigger it will focus on header 'Test' (if has).

```js
linktext: tarFile.path + '#Test'
```

**Comment by aoout** [comment]
I've got the rest of it done... but, the many highlights are now stored in a single markdown file, each separated by a simple delimiter. No headers, no block IDs. This all feels weird, and I need to redesign a data storage structure.

**Comment by playermiller109** [comment]
@aoout That's all right. This API can't be too smart. It's too much work. If there's a better way to do it later.

**Comment by aoout** [comment]
https://youtu.be/L3VM1d7Q_P0

**Comment by aoout** [comment]
Check out this video, which shows what the final result will look like. What do you think?

**Comment by aoout** [comment]
On the one hand, it is indeed much more convenient to edit comments. On the other hand, from some perspectives, the presentation of information is no longer elegant.

**Comment by playermiller109** [comment]
@aoout Congratulations first! Now it's my turn to be curious about how you did it, haha.

Regarding what you mentioned about having 2 different popovers for convenient editing and elegance, I have roughly two ideas.

The first one: Obsidian itself has a reading mode and an editing mode. You can choose which popover to use by detecting which mode users are currently in. For users, the reading mode is well-rendered with better layout, while the editing mode is for editing, which is also easy to understand.

```js
this.app.workspace.getActiveFileView().getMode()
// or this.app.workspace.getActiveFileView().currentMode.type
// could be more ways
```

Result 'source' is for editing mode and 'preview' is for reading mode.

<image width="300" src="https://github.com/aoout/obsidian-highlighter/assets/145541890/6105453b-47e5-4b3f-8903-0cca43d83fa5">

The second one: the plugin's current popover is written with `new HoverPopover()`, which is not limited to any specific trigger. The editable window is triggered with Ctrl, and this window can be triggered in other ways, so they don't interfere with each other, and users can choose whichever they want to see.

Take your time and don't stay up too late.

**Comment by aoout** [comment]
Thanks for your help. This is rare for me. Have a great night.

**Comment by aoout** [comment]
![image](https://github.com/aoout/obsidian-highlighter/assets/60838705/822609e8-7719-48a3-913b-a7b3582b1655)
By default, the corresponding popup is used in edit and read modes. However, you can also set it to always use one of them.

**Comment by playermiller109** [comment]
@aoout Good job! It turns out that you calculated the location of the highlight so that the popover can show the correct one. I have no further questions. Thanks for what you did.
